---
- name: Perform actions from inventory variables
  hosts: all
  vars:
    unit_name: gaiad
    regexp_line: '.+ committed state .+ height=\d{2,} .+'
  pre_tasks:
    - name: Create a check mode flag if running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: directory
        mode: "0644"
      check_mode: false
      when: ansible_check_mode
    - name: Remove the check mode flag if not running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: absent
      when: not ansible_check_mode
  tasks:
    - name: Check five-tests success cases
      ansible.builtin.include_tasks: "includes/success-all.yaml"
      when: "prop_mode in ['mod_start', 'start', 'stop']"

    - name: Check failure cases for stop manifests
      ansible.builtin.include_tasks: "includes/fail-stop.yaml"
      when: "prop_mode.startswith('stop_')"

    - name: Check failure cases for start manifests
      ansible.builtin.include_tasks: "includes/fail-start.yaml"
      when: "prop_mode.endswith('_fail')"
