---
- name: Perform actions from inventory variables
  hosts: all
  vars:
    unit_name: gaiad
  pre_tasks:
    - name: Create a check mode flag if running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: directory
        mode: "0644"
      check_mode: false
      when: ansible_check_mode
    - name: Remove the check mode flag if not running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: absent
      when: not ansible_check_mode
  tasks:
    - name: Start test service
      when: "prop_mode == 'start'"
      ansible.builtin.include_role:
        name: ansible-mega-launch
        tasks_from: mega-start.yaml
      vars:
        service_name: "{{ unit_name }}"
        port_list:
          - 9090
          - 9091
          - 26656
          - 26657
        log_regexp: '.+ committed state .+ height=\d{2,} .+'
        required_checks: 2
    - name: Stop test service
      when: "prop_mode == 'stop'"
      ansible.builtin.include_role:
        name: ansible-mega-launch
        tasks_from: mega-stop.yaml
      vars:
        service_name: "{{ unit_name }}"
        process_pattern: '.*\/bin\/{{ unit_name }} .*'
        port_list:
          - 9090
          - 9091
          - 26656
          - 26657

    - name: Start service for stop failure tests
      when: "prop_mode.startswith('stop_')"
      ansible.builtin.systemd:
        name: "{{ unit_name }}"
        force: yes
        no_block: no
        state: started
        daemon_reload: yes
      register: melau_result_systemd
      until: (melau_result_systemd.status.MainPID | int > 0 and
        melau_result_systemd.status.ActiveState == 'active') or ansible_check_mode
      retries: 3
      delay: 1

    - name: Block for stop failures
      when: "prop_mode.startswith('stop_')"
      block:
        - name: Stop wrong service to left ports open
          when: "prop_mode == 'stop_port'"
          ansible.builtin.include_role:
            name: ansible-mega-launch
            tasks_from: mega-stop.yaml
          vars:
            service_name: "sshd"
            max_rescues: 3
            rescue_delay: 1
            port_list:
              - 9090
              - 9091
              - 26656
              - 26657
        - name: Stop wrong service to left process
          when: "prop_mode == 'stop_proc'"
          ansible.builtin.include_role:
            name: ansible-mega-launch
            tasks_from: mega-stop.yaml
          vars:
            service_name: sshd
            process_pattern: '.*\/bin/{{ unit_name }} .*'
      rescue:
        - name: Set fact to success converge
          ansible.builtin.set_fact:
            rescue_happened: true

    - name: Check rescue happened
      when: "prop_mode.startswith('stop_') and not rescue_happened | default(false)"
      ansible.builtin.fail:
        msg: Rescue isn't happened when mega-stop should failure
