---
- name: Verify downloaded files
  hosts: all
  gather_facts: false
  vars:
    unit_name: gaiad
    prop_mode: "{{ lookup('ansible.builtin.env', 'ANSIBLE_PROP_MODE', default='none') }}"
  tasks:
    - name: Register service status
      ansible.builtin.systemd:
        name: "{{ unit_name }}"
      register: systemd_res

    - name: Assert service state
      ansible.builtin.assert:
        that: >-
          {%- set s_state = systemd_res.status.ActiveState == 'active' and
          systemd_res.status.SubState == 'running' -%}
          {%- if prop_mode in ('start', 'mod_start', 'start_run_fail', 'mod_run_fail',
          'stop_proc', 'stop_port') -%}
            {%- set result = s_state -%}
          {%- elif prop_mode in ('start_non_fail', 'mod_non_fail', 'stop') -%}
            {%- set result = not s_state -%}
          {%- else -%}
            {%- set result = false -%}
          {%- endif -%}
          {{- result | bool -}}
        fail_msg: >-
          service [{{ unit_name }}] unexpected [{{ systemd_res.status.ActiveState }}]
          state [{{ systemd_res.status.SubState }}] sub [{{ prop_mode }}] mode
        success_msg: >-
          service [{{ unit_name }}] expected [{{ systemd_res.status.ActiveState }}]
          state [{{ systemd_res.status.SubState }}] sub [{{ prop_mode }}] mode
